import { IRepositoryProvider } from '../../src/repository/providers/provider.repository.interface';

export const mockUris = async (repositoryProvider: IRepositoryProvider) => {
  await repositoryProvider.save({
    id: 'idr/01/09359502000041',
    namespace: 'idr',
    identificationKeyType: 'gtin',
    identificationKey: '9359502000041',
    itemDescription: 'DPP',
    qualifierPath: '/',
    active: true,
    responses: [
      {
        targetUrl: 'http://example-json.com.au',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'au',
        mimeType: 'application/json',
        active: true,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
      {
        targetUrl: 'http://example-html.com.au',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'au',
        mimeType: 'text/html',
        active: true,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: true,
      },
      {
        targetUrl: 'http://example-json.com',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'us',
        mimeType: 'application/json',
        active: true,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
      {
        targetUrl: 'http://example-html.com',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'us',
        mimeType: 'text/html',
        active: true,
        fwqs: false,
        defaultLinkType: true,
        defaultIanaLanguage: true,
        defaultContext: true,
        defaultMimeType: true,
      },
    ],
    linkset: {
      anchor: 'http://localhost:3000/01/09359502000041',
      itemDescription: 'Passport',
      'https://idr.com/voc/defaultLink': [
        {
          href: 'http://example-json.com',
          title: 'Passport',
        },
      ],
      'https://idr.com/voc/defaultLinkMulti': [
        {
          href: 'http://example-html.com',
          title: 'Passport',
          type: 'text/html',
          hreflang: ['en'],
        },
        {
          href: 'http://example-html.com.au',
          title: 'Passport',
          type: 'text/html',
          hreflang: ['en'],
        },
      ],
      'https://idr.com/voc/certificationInfo': [
        {
          href: 'http://example-json.com',
          title: 'Passport',
          type: 'application/json',
          hreflang: ['en'],
        },
        {
          href: 'http://example-html.com',
          title: 'Passport',
          type: 'text/html',
          hreflang: ['en'],
        },
        {
          href: 'http://example-json.com.au',
          title: 'Passport',
          type: 'application/json',
          hreflang: ['en'],
        },
        {
          href: 'http://example-html.com.au',
          title: 'Passport',
          type: 'text/html',
          hreflang: ['en'],
        },
      ],
    },
    linkHeaderText:
      '<http://example-json.com>; rel="idr:certificationInfo"; type="application/json"; hreflang="en"; title="Passport", <http://example-html.com>; rel="idr:certificationInfo"; type="text/html"; hreflang="en"; title="Passport", <http://example-json.com.au>; rel="idr:certificationInfo"; type="application/json"; hreflang="en"; title="Passport", <http://example-html.com.au>; rel="idr:certificationInfo"; type="text/html"; hreflang="en"; title="Passport", <https://id.idr.org/01/09359502000041>; rel="owl:sameAs"',
  });

  await repositoryProvider.save({
    id: 'idr/01/09359502000042',
    namespace: 'idr',
    identificationKeyType: 'gtin',
    identificationKey: '9359502000042',
    itemDescription: 'DPP',
    qualifierPath: '/',
    active: true,
    responses: [
      {
        targetUrl: 'http://example-json.com.au',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'au',
        mimeType: 'application/json',
        active: true,
        fwqs: true,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
      {
        targetUrl: 'http://example-html-inactive.com',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'us',
        mimeType: 'text/html',
        active: false,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
      {
        targetUrl: 'http://example-html-active.com',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'us',
        mimeType: 'text/html',
        active: true,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
    ],
    linkset: {
      anchor: 'http://localhost:3000/01/09359502000042',
      itemDescription: 'Passport',
      'https://idr.com/voc/defaultLink': [],
      'https://idr.com/voc/defaultLinkMulti': [],
      'https://idr.com/voc/certificationInfo': [
        {
          href: 'http://example-json.com',
          title: 'Passport',
          type: 'application/json',
          hreflang: ['en'],
        },
        {
          href: 'http://example-html.com',
          title: 'Passport',
          type: 'text/html',
          hreflang: ['en'],
        },
      ],
    },
    linkHeaderText:
      '<http://example-json.com>; rel="idr:certificationInfo"; type="application/json"; hreflang="en"; title="Passport", <http://example-html.com>; rel="idr:certificationInfo"; type="text/html"; hreflang="en"; title="Passport", <https://id.idr.org/01/09359502000041>; rel="owl:sameAs"',
  });

  await repositoryProvider.save({
    id: 'idr/01/09359502000043',
    namespace: 'idr',
    identificationKeyType: 'gtin',
    identificationKey: '9359502000043',
    itemDescription: 'DPP',
    qualifierPath: '/',
    active: false,
    responses: [
      {
        targetUrl: 'http://example-json.com.au',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'au',
        mimeType: 'application/json',
        active: true,
        fwqs: true,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
      {
        targetUrl: 'http://example-html-inactive.com',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'us',
        mimeType: 'text/html',
        active: false,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
      {
        targetUrl: 'http://example-html-active.com',
        title: 'Passport',
        linkType: 'idr:certificationInfo',
        ianaLanguage: 'en',
        context: 'us',
        mimeType: 'text/html',
        active: true,
        fwqs: false,
        defaultLinkType: false,
        defaultIanaLanguage: false,
        defaultContext: false,
        defaultMimeType: false,
      },
    ],
    linkset: {
      anchor: 'http://localhost:3000/01/09359502000043',
      itemDescription: 'Passport',
      'https://idr.com/voc/defaultLink': [],
      'https://idr.com/voc/defaultLinkMulti': [],
      'https://idr.com/voc/certificationInfo': [
        {
          href: 'http://example-json.com',
          title: 'Passport',
          type: 'application/json',
          hreflang: ['en'],
        },
        {
          href: 'http://example-html.com',
          title: 'Passport',
          type: 'text/html',
          hreflang: ['en'],
        },
      ],
    },
    linkHeaderText:
      '<http://example-json.com>; rel="idr:certificationInfo"; type="application/json"; hreflang="en"; title="Passport", <http://example-html.com>; rel="idr:certificationInfo"; type="text/html"; hreflang="en"; title="Passport", <https://id.idr.org/01/09359502000041>; rel="owl:sameAs"',
  });
};
